# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

# Not working well, still figuring out how to tweak Goreleaser Free :/

version: 2
pro: false

project_name: downjack

before:
  hooks:
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

#aur_sources:
#  - maintainers:
#      - "Charles Dong <chardon_cs@proton.me>"
#    description: "Set up your gitignore and license files like using a lumberjack"
#    homepage: "https://github.com/chardoncs/downjack"
#    license: "MIT"
#
#    private_key: "{{ .Env.AUR_KEY }}"
#    git_url: "ssh://aur@aur.archlinux.org/downjack-bin.git"
#
#    provides:
#      - downjack
#
#    conflicts:
#      - downjack
#
#    depends:
#      - git
#
#aurs:
#  - maintainers:
#      - "Charles Dong <chardon_cs@proton.me>"
#    description: "Set up your gitignore and license files like using a lumberjack"
#    homepage: "https://github.com/chardoncs/downjack"
#    license: "MIT"
#
#    private_key: "{{ .Env.AUR_KEY }}"
#    git_url: "ssh://aur@aur.archlinux.org/downjack-bin.git"
#
#    provides:
#      - downjack
#
#    conflicts:
#      - downjack
#
#    depends:
#      - git
